version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8.18
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Installing AWS CLI and dependency
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
            sudo pip3 install --upgrade pip
      - run: pip3 install -r requirements.txt && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver


workflows:
  current-workflow:
    jobs:
    - build