version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
  aws-code-deploy: circleci/aws-code-deploy@3.0
workflows:
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: aws-cicd-app
          auth:
            - aws-cli/setup
          bundle-bucket: insightai-cicd
          bundle-key: arn:aws:s3:::insightai-cicd/appdirectory/
          deployment-group: aws-cicd-dep-group
          service-role-arn: arn:aws:iam::282765282943:role/CodeDeployRole
