version: 2.1

jobs:

  build-and-push-to-dockerhub:
      docker:
        - image: cimg/python:3.8.18
      steps:
        - checkout
        - setup_remote_docker:
            version: 19.03.13
            docker_layer_caching: true
        
        - run: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
        - run: docker build -t user_name/aws-cicd:$CIRCLE_BRANCH 
        - run: docker push user_name/circlehubrepo:$CIRCLE_BRANCH


workflows:
  my-workflow:
    jobs:
     - build-and-push-to-dockerhub



