version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8.18
    resource_class: medium
    steps:
      - checkout
      - run: cd ./app && pip3 install -r requirements.txt && python3 runserver manage.py
      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - .

workflows:
  InsightAI-workflow:
    jobs:
    - build